#add the files to index
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_001
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_002
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_003
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_004
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_005
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_006
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_007
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_008
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_009
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_010
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_011
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_012
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_013
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_014
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_015
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_016
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_017
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_018
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_019
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_020
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_021
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_022
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_023
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_024
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_025
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_026
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_027
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_028
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_029
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_030
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_031
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_032
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_033
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_034
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_035
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_036
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_037
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_038
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_039
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_040
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_041
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_042
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_043
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_044
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_045
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_046
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_047
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_048
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_049
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_050
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_051
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_052
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_053
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_054
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_055
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_056
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_057
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_058
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_059
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_060
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_061
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_062
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_063
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_064
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_065
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_066
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_067
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_068
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_069
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_070
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_071
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_072
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_073
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_074
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_075
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_076
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_077
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_078
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_079
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_080
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_081
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_082
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_083
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_084
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_085
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_086
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_087
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_088
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_089
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_090
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_091
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_092
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_093
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_094
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_095
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_096
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_097
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_098
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_099
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_100
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_101
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_102
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_103
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_104
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_105
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_106
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_107
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_108
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_109
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_110
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_111
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_112
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_113
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_114
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_115
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_116
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_117
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_118
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_119
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_120
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_121
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_122
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_123
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_124
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_125
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_126
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_127
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_128
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_129
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_130
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_131
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_132
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_133
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_134
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_135
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_136
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_137
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_138
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_139
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_140
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_141
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_142
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_143
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_144
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_145
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_146
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_147
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_148
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_149
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_150
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_151
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_152
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_153
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_154
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_155
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_156
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_157
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_158
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_159
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_160
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_161
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_162
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_163
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_164
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_165
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_166
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_167
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_168
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_169
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_170
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_171
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_172
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_173
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_174
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_175
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_176
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_177
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_178
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_179
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_180
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_181
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_182
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_183
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_184
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_185
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_186
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_187
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_188
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_189
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_190
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_191
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_192
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_193
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_194
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_195
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_196
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_197
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_198
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_199
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_200
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_001
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_002
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_003
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_004
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_005
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_006
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_007
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_008
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_009
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_201
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_010
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_011
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_012
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_013
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_014
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_015
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_016
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_017
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_018
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_019
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_202
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_020
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_021
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_022
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_023
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_024
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_025
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_026
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_027
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_028
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_029
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_203
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_030
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_031
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_032
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_033
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_034
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_035
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_036
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_037
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_038
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_039
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_204
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_040
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_041
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_042
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_043
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_044
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_045
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_046
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_047
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_048
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_049
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_205
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_050
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_051
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_052
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_053
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_054
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_055
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_056
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_057
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_058
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_059
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_206
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_060
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_061
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_062
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_063
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_064
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_065
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_066
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_067
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_068
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_069
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_207
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_070
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_071
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_072
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_073
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_074
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_075
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_076
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_077
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_078
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_079
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_208
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_080
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_081
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_082
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_083
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_084
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_085
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_086
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_087
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_088
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_089
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_209
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_090
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_091
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_092
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_093
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_094
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_095
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_096
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_097
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_098
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_099
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_210
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_100
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_101
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_102
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_103
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_104
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_105
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_106
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_107
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_108
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_109
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_211
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_110
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_111
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_112
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_113
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_114
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_115
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_116
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_117
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_118
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_119
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_212
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_120
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_121
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_122
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_123
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_124
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_125
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_126
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_127
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_128
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_129
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_213
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_130
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_131
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_132
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_133
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_134
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_135
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_136
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_137
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_138
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_139
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_214
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_140
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_141
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_142
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_143
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_144
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_145
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_146
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_147
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_148
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_149
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_215
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_150
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_151
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_152
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_153
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_154
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_155
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_156
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_157
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_158
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_159
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_216
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_160
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_161
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_162
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_163
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_164
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_165
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_166
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_167
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_168
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_169
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_217
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_170
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_171
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_172
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_173
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_174
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_175
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_176
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_177
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_178
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_179
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_218
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_180
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_181
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_182
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_183
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_184
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_185
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_186
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_187
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_188
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_189
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_219
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_190
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_191
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_192
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_193
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_194
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_195
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_196
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_197
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_198
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_199
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_220
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_200
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_201
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_202
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_203
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_204
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_205
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_206
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_207
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_208
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_209
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_221
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_210
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_211
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_212
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_213
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_214
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_215
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_216
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_217
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_218
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_219
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_222
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_220
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_221
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_222
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_223
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_224
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_225
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_226
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_227
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_228
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_229
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_223
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_230
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_231
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_232
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_233
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_234
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_235
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_236
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_237
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_238
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_239
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_224
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_240
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_241
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_242
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_243
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_244
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_245
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_246
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_247
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_248
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_249
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_225
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_250
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_251
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_252
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_253
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_254
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_255
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_256
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_257
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_258
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_259
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_226
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_260
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_261
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_262
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_263
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_264
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_265
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_266
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_267
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_268
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_269
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_227
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_270
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_271
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_272
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_273
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_274
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_275
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_276
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_277
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_278
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_279
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_228
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_280
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_281
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_282
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_283
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_284
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_285
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_286
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_287
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_288
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_289
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_229
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_290
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_291
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_292
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_293
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_294
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_295
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_296
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_297
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_298
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_299
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_230
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_300
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_301
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_302
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_303
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_304
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_305
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_306
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_307
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_308
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_309
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_231
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_310
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_311
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_312
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_313
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_314
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_315
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_316
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_317
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_318
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_319
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_232
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_320
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_321
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_322
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_323
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_324
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_325
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_326
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_327
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_328
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_329
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_233
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_330
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_331
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_332
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_333
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_334
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_335
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_336
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_337
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_338
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_339
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_234
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_340
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_341
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_342
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_343
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_344
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_345
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_346
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_347
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_348
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_349
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_235
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_350
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_351
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_352
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_353
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF2_354
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_236
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_237
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_238
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_239
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_240
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_241
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_242
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_243
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_244
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_245
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_246
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_247
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_248
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_249
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_250
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_251
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_252
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_253
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_254
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_255
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_256
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_257
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_258
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_259
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_260
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_261
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_262
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_263
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_264
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_265
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_266
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_267
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_268
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_269
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_270
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_271
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_272
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_273
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_274
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_275
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_276
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_277
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_278
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_279
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_280
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_281
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_282
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_283
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_284
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_285
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_286
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_287
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_288
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_289
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_290
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_291
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_292
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_293
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_294
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_295
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_296
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_297
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_298
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_299
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_300
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_301
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_302
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_303
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_304
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_305
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_306
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_307
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_308
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_309
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_310
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_311
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_312
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_313
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_314
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_315
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_316
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_317
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_318
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_319
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_320
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_321
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_322
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_323
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_324
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_325
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_326
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_327
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_328
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_329
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_330
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_331
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_332
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_333
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_334
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_335
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_336
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_337
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_338
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_339
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_340
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_341
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_342
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_343
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_344
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_345
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_346
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_347
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_348
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_349
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_350
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_351
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_352
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_353
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_354
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_355
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_356
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_357
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_358
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_359
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_360
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_361
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_362
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_363
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_364
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_365
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_366
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_367
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_368
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_369
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_370
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_371
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_372
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_373
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_374
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_375
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_376
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_377
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_378
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_379
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_380
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_381
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_382
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_383
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_384
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_385
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_386
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_387
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_388
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_389
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_390
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_391
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_392
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_393
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_394
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_395
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_396
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_397
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_398
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_399
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_400
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_401
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_402
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_403
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_404
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_405
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_406
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_407
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_408
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_409
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_410
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_411
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_412
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_413
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_414
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_415
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_416
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_417
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_418
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_419
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_420
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_421
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_422
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_423
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_424
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_425
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_426
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_427
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_428
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_429
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_430
/home/kunal/Desktop/IR_Project/Data_Sets/Extracted/ZF/ZF_431
